### ISSUE TITLE
"Failed to retrieve main contact"

### ISSUE THREAD

**Issue by ajmeier29** [stakwork/sphinx-relay#218]
I am following the documentation to run sphinx-relay on mynode. I have generated the QR code and attempted to login on the android app. I scan the QR Code, it asks me for a pin 2 times, then I type in a name and I get "Failed to retrieve main contact". I'm not sure if I have missed a step or not, but it's hard for me to debug the issue as I only have that toast message and no log.

**Comment by tomastiminskas** [comment]
The "Failed to retrieve main contact" error message is saying the GET /contacts endpoint is returning error during signup. The only way to know the cause of the issue is checking relay logs while signing up to understand why that endpoint is failing. I would suggest to reset relay, reset data on app (or uninstall it) and signup again while tailing relay logs.
