### ISSUE TITLE
Direct payments in tribes

### ISSUE THREAD

**Issue by Evanfeenstra** [stakwork/sphinx-relay#348]
We should support direct payments in tribes. This will enable paying out bounties directly in tribes, possibly even directly from GitBot, so everyone can see. What design/network additions are there?

We probably need the recipients `alias` listed on the payment? Like "Joe received 1000 sats!" 
- Updated design for the payment row? @Antanasijevic what do you think?
- New column on `Message` table like `recipient_alias` 
- New corresponding field in the LUMO message format

**Comment by Antanasijevic** [comment]
Since we already have these options in different places, in app and on people page, i think we should try to make all these actions as consistent as possible. 

**Questions:**
- On People page, user can connect with other user, or donate him sats without connecting. For consistency purposes, should we keep same flow in app?

- When sending payment to other, not connected user, should we continue using Donate widget as we do on people page, or we want to send simple payment, like we can do from dashboard bottom bar?

**Suggestions**:
Tap on not connected tribe member should open same dialog as one that opens when connecting with someone on people page. (With some layout improvements and necessary variations). Dialog will show Profile image, name, price to connect, and two buttons - "Connect" and "Send Payment" (Labels may be different in final version).

For connected users we should have a proper profile page, with about section (same content as on People page) and transaction list.

![image](https://user-images.githubusercontent.com/13258550/162448505-8448938c-291d-4e31-b656-3d536b867ed5.png)

**Comment by Evanfeenstra** [comment]
Very nice. I think we need a little mockup of what a payment in a tribe looks like @Antanasijevic. Like a direct payment in a 1-to-1 chat, but with the alias... "You paid Joe 1000 sats!"

On the technical side I think there are a few possible courses of action here:

- make it consistent with people page. I mean, you only need the user's pubkey, and then you can query people DB for more info about them. BUT that requires everyone to sign up on people page first

- make new columns in the tribe admin's ChatMembers table. But that would require a new keysend message type like `group_profile` that the user needs to publish in order to be public in the group. And i'm not sure how to "query" that information from tribe admin unless its included in every single message which seems overkill

- just use the user's `alias`, which is already in each message. But of course payments could fail if alias changed, or the user left the group

- start including the msg sender's ID in each message, then at least they can send them a payment in the tribe easily.

**Comment by Antanasijevic** [comment]
When it comes to visible direct payment inside the tribe, it will have to look something like this.
This layout is in line with the other payment/boost variations we planned.
Tap on item may open a dialog with transaction details

![image](https://user-images.githubusercontent.com/13258550/162791460-ee67e3d0-cf21-491f-ac79-2c31a32c162e.png)

**Comment by kevkevinpal** [comment]
> * that the user needs to publish in order to be public in the group.

If we used alias would that cause issues if the user wanting sats to be sent to them were part of two tribes from the same owner but had two different alias on each tribe? Since the contactId would be the same and would update the lastAlias?

**Comment by Evanfeenstra** [comment]
> > ```
> > * start including the msg sender's ID in each message, then at least they can send them a payment in the tribe easily.
> > ```
> 
> Is this not the same value? If it is we might be able to use it https://github.com/stakwork/sphinx-relay/blob/v2.2.7/src/models/sql/message.ts#L23

Ya the ID is available of course, but when messages are forwarded to tribes, the receiver only actually gets the tribe admin's info. This was decided to increase privacy (user's pubkeys are never revealed).

**Comment by Evanfeenstra** [comment]
> > just use the user's alias, which is already in each message. But of course payments could fail if alias changed, or the user left the group
> 
> @Evanfeenstra If we used alias would that cause issues if the user wanting sats to be sent to them were part of two tribes from the same owner but had two different alias on each tribe? Since the contactId would be the same and would update the lastAlias?

Nope there is a table called ChatMembers that stores the "last used alias" from each member in each of your tribes. Using this value could cause a problem though because you might want to send sats to someone, but they may have changed their alias in the meantime, so they would not be found...

**Comment by kevkevinpal** [comment]
@Evanfeenstra how do we currently send boosts could it not be similar? I'm not too familiar with the boost code but we can do that through group messages already

**Comment by Evanfeenstra** [comment]
> @Evanfeenstra how do we currently send boosts could it not be similar? I'm not too familiar with the boost code but we can do that through group messages already

With a boost you have the message uuid that you are boosting. With that, the tribe admin can infer the pubkey of the sender of the original message. So yes, we just need to pick which "identifier" to use when we don't have that message uuid to use

**Comment by tomastiminskas** [comment]
@Evanfeenstra @kevkevinpal I think we have 2 options for this. 

### OPTION 1
The simplest option would be to just allow a tribe member to send a direct payment to a message sender. So you tap on a message sender small picture and you are taken to a simple profile view showing `alias, image` (which are already available on the message record) and a button to send direct payment. Or even just add an option on the message menu on long press. The only addition needed would be `recipient_alias` and `recipient_photo_url`. And we can use message `uuid` as identifier on the direct payment so admin can identify the message, then identify the sender and send it. 

### OPTION 2
The other option would be a more complex and big feature integrating member, admin and people server (this could definitely be useful for new features in the future). This is just a draft of the first way I could think to implement this, but open to suggestions or changes:
- MEMBER
      1. Ability to set profile as public on a specific tribe. To do this user needs to create a profile on ppl site (this will increase numbers of profiles on ppl site significantly)
      2. User sets his profile as PUBLIC on people site for a specific tribe. New table on ppl site with following columns: `tribe_uuid, profile_id, tribe_profile_uuid` (this last value will be a UUID to identify that user on that tribe and each time a member sets his profile as public on a specific tribe it will be generated again).
      3. Member sends his `tribe_profile_uuid` of the ppl site to the tribe ADMIN. 
- ADMIN
      1. Stores `profile_tribe_uuid` on tribe members table
      2. Starts sending that uuid as `sender_uuid` on each message
- ANOTHER MEMBER IN THE TRIBE
      1. Can request ppl server with `tribe_uuid` and get list of public members on that tribe. Then access profile of any of them
      2. Can request ppl server with `tribe_profile_uuid` took from a message and get basic profile information of that message sender (if message contains a `sender_uuid` it means the member was PUBLIC at the time he sent the message. if ppl site returns a valid profile when requested using that `uuid` it means it is still a public member).
      3. Can send direct_payment using that `sender_uuid` through admin or add contact (with price to connect if set) from the profile returned from ppl server
- MEMBER: 
      1. If member sets his profile back as private on that tribe, the record on ppl server is deleted and a message is send to ADMIN so the `tribe_profile_uuid` is removed from tribe members table on admin node. So admin will stop sending it on each message sent by that user on the tribe. Even if he continues sending it, ppl site won't return the profile anymore since the record on ppl server that linked the user with the tribe was deleted. User won't be returned on list of public members anymore. 
      2. If member sets his profile as public again a new record with a new `tribe_profile_uuid` will be created so old message sent by that user will lose the reference to the profile on ppl site.

**Comment by Evanfeenstra** [comment]
I really like Option 1 :) because it is a simple change (pretty much the same as `boost` logic), and preserves privacy. People can already publish profiles on the people page, for anyone to be able to pay them. But it maybe is not the most intuitive UX (to need to tap a message to pay someone)

There is also Option 3: no involvement of people page. Instead, its just a setting that a tribe member can make to include their own `pubkey` in each message in a tribe. Pubkey is the only thing needed to pay someone really

**Comment by kevkevinpal** [comment]
> I really like Option 1 :) because it is a simple change (pretty much the same as `boost` logic), and preserves privacy. People can already publish profiles on the people page, for anyone to be able to pay them. But it maybe is not the most intuitive UX (to need to tap a message to pay someone)
> 
> There is also Option 3: no involvement of people page. Instead, its just a setting that a tribe member can make to include their own `pubkey` in each message in a tribe. Pubkey is the only thing needed to pay someone really. But that would actually be pretty complicated, with new columns and `tribe_settings` message type... and would change the tribe auth structure (where now the tribe `uuid` is a signature created from the admin's key, so each message content is verified at each node)

Isn't there more UX limitations with #1 because we won't be able to add a contact since the pubkey isn't available? And we're only using the alias to send the payment

**Comment by tomastiminskas** [comment]
@kevkevinpal we will be using message uuid to send the payment and yes, we won't be able to add the contact, just send direct payments.

**Comment by Antanasijevic** [comment]
> I really like Option 1 :) because it is a simple change (pretty much the same as `boost` logic), and preserves privacy. People can already publish profiles on the people page, for anyone to be able to pay them. But it maybe is not the most intuitive UX (to need to tap a message to pay someone)

In this scenario, user will tap on profile picture not on message. Tap on profile picture will open small dialog with Profile picture, name and button for direct payment, and later maybe button for direct messaging. You can see mockup of this earlier in this ticket.
Tap on message opens options related to that particular message only.

**Comment by tomastiminskas** [comment]
@Antanasijevic that makes total sense. But I would change the small dialog to show name and picture as you said, and directly there a field to enter the amount to send and the button to confirm. It will be the only action allowed so having a second dialog for the direct payment itself seems too much IMO.

**Comment by tomastiminskas** [comment]
@Antanasijevic We can't use the donate widget because without the user public key we can't set up a recurring payment. It will be a one time payment sent to the message sender where you tap on the profile picture.

**Comment by Antanasijevic** [comment]
> @Antanasijevic that makes total sense. But I would change the small dialog to show name and picture as you said, and directly there a field to enter the amount to send and the button to confirm. It will be the only action allowed so having a second dialog for the direct payment itself seems too much IMO.

Simple input field and confirm button can work well, as long as it is only action offered on the dialog.
Once we add "Connect" button (for Direct messaging) payment will have to go on new dialog.

**Comment by tomastiminskas** [comment]
@Antanasijevic I'm checking options and as we could support payment with comment, maybe we can just show the SEND PAYMENT button on the dialog (along with the name and image of the user) and when tapped present the Payment view (the one with the message field at the top and the keypad to set the amount). That would be consistent with sending a direct payment on a conversation chat and will allow to set a message too. 

@Evanfeenstra this pattern should support a direct payment with a message, right?

**Comment by kevkevinpal** [comment]
ok so I'm not 100% sure if this could work but instead of asking for someone to send their pubkey we can instead try to privately communicate our pubkeys by using our pubkey as a private key


```
This is computed by sender
d_A = private key (will be using our pubkey as a privatekey)
G = some public point on the eliptic curve
Q_A = d_A * G

Send over -> Q_A and G

Receiver (Person you want to add)
r = random value they generate (keep private)
R = r * G
S = r * Q_A (Keep this is the symmetric key we will use)

Send over R -> 

Sender
S = d_A * R
S = d_A * (r * G) (remember you don't know r but R = (r*G))
S = r * (d_A * G) (move around values since you can do that with multiplication)
S = r * Q_A (Same as what the receiver made)
```

Now you can successfully send over d_A using the symetric key S using symetric key encryption like AES

Below is a good video that sums it up pretty well

https://www.youtube.com/watch?v=saZj0ZKRNl0&ab_channel=BillBuchananOBE

I think this'll work but I'd want someone to look it over as I'm not an expert at this and also this is not a quick solution since this'll definitely take some time to get working

This is also what we were looking at when we wanted to upgrade to tink so it seems it might be useful in multiple scenarios

let me know what you think :)

**Comment by kevkevinpal** [comment]
Also the above comment isn't in total regards to direct payment more so for adding a person as a contact in a tribe privately

**Comment by Evanfeenstra** [comment]
I think we need to discuss this in a meeting, including Paul :) I don't want to overcomplicate things: The People Page is where people can go to share their pubkey already, so is it really needed to add that feature into tribes too? It may confuse people tbh, if there are too many options...

**Comment by kevkevinpal** [comment]
Yea definitely, I do know people have been requesting the feature to be able to add people from a group chat but seems like it'll be kinda complicated to do that privately and without having the tribe owner facilitate the exchange

**Comment by tomastiminskas** [comment]
So we could start building a simpler first version as we discussed where user can tap on a profile picture (or initial circle) of a message on a tribe and send a direct payment to it using the UUID of the message. Then admin will find the message sender of that message and send it inside the tribe to all (through MQTT) and to the message sender (through lightning) with the right amount (same as with boost messages)

- We can use the existing send payment endpoint supporting a new param (message_uuid) or build a new endpoint for this. Up to you
- `recipient_alias` and `recipient_pic` need to be added to Message model. Those will be set in this case (so apps shows it as a direct payment between members on a tribe)

@Evanfeenstra @kevkevinpal if you do the relay changes and deploy to my two nodes, then I can test both sides (member and admin) Let me know what do you think

**Comment by Evanfeenstra** [comment]
Ya I can work on that... let use the same endpoint that messages and boosts use (since the logic is mostly there already for boosts). But instead of a `boost` boolean in the body, lets make it a `pay` boolean.

**Comment by tomastiminskas** [comment]
@Evanfeenstra makes sense. I guess this can support a message with the payment, right? 

Thinking about it because on the case of a boost we use a json as messageContent and it contains the message and the amount. 

But on the case of a direct payment inside a tribe, we can use messageContent for the message itself (if it exists) and the amount as amount. So no need to have a json as messageContent. You will set the type as direct payment if the `pay` param comes in, and set `recipient_alias` and `recipient_pic`. As I described in the previous comment, the pmt should go to the receiver through lightning and to the rest of the members through MQTT. 

Makes sense? or am I missing something?

**Comment by tomastiminskas** [comment]
@Antanasijevic Posting here how the first version of direct payments in tribes work and look. 

**I IMPROVED THE NORMAL PAYMENT ROWS TO ADAPT ITS WIDTH TO THE CONTENT. THEY HAD A FIXED WIDTH ON KOTLIN BEFORE.** 
![Pmts1](https://user-images.githubusercontent.com/2242281/164550781-6c2cac10-76f9-42a7-bab3-ef75257658c4.jpg)

**TO SEND A DIRECT PAYMENT ON A TRIBE YOU NEED TO TAP ON THE PROFILE PICTURE OF A RECEIVED MESSAGE**
![Pmts2](https://user-images.githubusercontent.com/2242281/164550893-12b01a6c-c906-44c8-bc5c-f05613b9d1b5.jpg)

**IT WILL OPEN A POPUP THAT SHOWS MESSAGE SENDER ALIAS AND PICTURE AND A BUTTON TO SEND SATS**
![Pmts3](https://user-images.githubusercontent.com/2242281/164550994-bcfc4a50-2235-4ccd-add9-cb5abce2de00.jpg)

**TAPPING ON SEND SATS BUTTON IT WILL OPEN THE SEND PMT VIEW WE ALREADY HAVE WITH THE DESTINATION INFO ON THE TOP**
![Pmts4](https://user-images.githubusercontent.com/2242281/164551057-25f1f322-2a79-4786-9f71-e918eba2fa39.jpg)

**PAYMENTS ON TRIBES WILL LOOK LIKE THIS WHEN SENT (Tomorrow I will be testing and uploading screenshots of received tribe payments). THE ONLY DIFFERENCE WITH THE ROW DESIGNS ON THIS TICKET IS THAT THE TEXT SHOWS BELOW THE PMT INSTEAD OF ABOVE (because the structure of the row is done that way for normal direct payments)**
![Pmts5](https://user-images.githubusercontent.com/2242281/164551157-dea436bd-d0b0-4f9c-b27b-bfabcfe68ab8.jpg)

This is a simple first version but we did it backward compatible. It means that if user has no updated relay or app and receives one of this, the payment won't show recipient info, but it won't break the layouts at all. It will just show as a normal direct payment on the tribe chat

**Comment by Antanasijevic** [comment]
Here are updates on basic UI elements for direct payment in tribes.
If possible, i think we should make a difference between existing and New contact when sending direct payment in tribes.
New contact should be presented with a simple pop up, while tap on existing contact will open a profile page of selected person.
What do you think?

Figma project for these screens
https://www.figma.com/file/ubLDYAiOPpABfWl7X68pad/Dark_Version_375x667?node-id=3194%3A117994

![image](https://user-images.githubusercontent.com/13258550/165357040-7c92e811-eb45-42a9-90d4-582a174146e4.png)

**Comment by kevkevinpal** [comment]
Adding these for tracking
https://github.com/stakwork/sphinx-kotlin/pull/451
https://github.com/stakwork/sphinx-relay/pull/363
