### ISSUE TITLE
app displaying in top LHS to upgrade app yet no upgrade appears to exists in ios app store

### ISSUE THREAD

**Issue by flyingisawol** [stakwork/sphinx-relay#567]
is there an update somewhere else ?

**Comment by kevkevinpal** [comment]
@tomastiminskas not sure if you can help with this?

**Comment by tomastiminskas** [comment]
@flyingisawol as we are blocked in the App Store we started to release app using Test Flight since several months ago. 

To install latest iOS version you should follow the steps below:
- Install Test Flight app from App Store on your device
- Follow this link and the steps in it to join the public beta: https://testflight.apple.com/join/QoaCkJn6

**Comment by kevkevinpal** [comment]
@tomastiminskas response should be sufficient to get the newest version, I will close the issue now. Please reopen if you continue to have problems :)
